// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiendaServicios.Api.CarritoCompra.Persistence;

namespace TiendaServicios.Api.CarritoCompra.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TiendaServicios.Api.CarritoCompra.Model.SessionShoppingCart", b =>
                {
                    b.Property<int>("SessionShopingCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.HasKey("SessionShopingCartId");

                    b.ToTable("sessionShoppingCarts");
                });

            modelBuilder.Entity("TiendaServicios.Api.CarritoCompra.Model.SessionShoppingCartDetail", b =>
                {
                    b.Property<int>("SessionShoppingCartDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ProductSelected")
                        .HasColumnType("text");

                    b.Property<int>("SessionShopingCartId")
                        .HasColumnType("int");

                    b.Property<int?>("SessionShoppingCartSessionShopingCartId")
                        .HasColumnType("int");

                    b.HasKey("SessionShoppingCartDetailId");

                    b.HasIndex("SessionShoppingCartSessionShopingCartId");

                    b.ToTable("sessionShoppingCartDetails");
                });

            modelBuilder.Entity("TiendaServicios.Api.CarritoCompra.Model.SessionShoppingCartDetail", b =>
                {
                    b.HasOne("TiendaServicios.Api.CarritoCompra.Model.SessionShoppingCart", null)
                        .WithMany("Details")
                        .HasForeignKey("SessionShoppingCartSessionShopingCartId");
                });
#pragma warning restore 612, 618
        }
    }
}
