// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TiendaServicios.API.Autor.Persitence;

namespace TiendaServicios.API.Autor.Migrations
{
    [DbContext(typeof(ContextAuthor))]
    [Migration("20200827010109_InitialMigrationPostgress")]
    partial class InitialMigrationPostgress
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TiendaServicios.API.Autor.Model.AcademicGrade", b =>
                {
                    b.Property<int>("AcademicGradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("AcademicDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("AcademicGradeGuid")
                        .HasColumnType("text");

                    b.Property<string>("AcademicGradeName")
                        .HasColumnType("text");

                    b.Property<string>("AcademicPlace")
                        .HasColumnType("text");

                    b.Property<int>("BookAuthorId")
                        .HasColumnType("integer");

                    b.HasKey("AcademicGradeId");

                    b.HasIndex("BookAuthorId");

                    b.ToTable("academicGrades");
                });

            modelBuilder.Entity("TiendaServicios.API.Autor.Model.BookAuthor", b =>
                {
                    b.Property<int>("IdBookAuthor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AuthorLibroGuid")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BookAuthorBirthName")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("BookAuthorLastName")
                        .HasColumnType("text");

                    b.Property<string>("BookAuthorName")
                        .HasColumnType("text");

                    b.HasKey("IdBookAuthor");

                    b.ToTable("bookAuthors");
                });

            modelBuilder.Entity("TiendaServicios.API.Autor.Model.AcademicGrade", b =>
                {
                    b.HasOne("TiendaServicios.API.Autor.Model.BookAuthor", "bookAuthor")
                        .WithMany("AcademicGrades")
                        .HasForeignKey("BookAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
